{"cells":[{"cell_type":"markdown","metadata":{"id":"_mUAX9N8t2Bh"},"source":["# Recitation 0G: Debugging of Deep Neural Network (Part 2)"]},{"cell_type":"markdown","metadata":{"id":"Qf66VApSt2Bh"},"source":["##Main purpose of this notebook: \n","1. How to read traceback \\\n","2. How to use pdb for interactive debugging"]},{"cell_type":"markdown","metadata":{"id":"UcBDzc80t2Bh"},"source":["## Reading Traceback\n","\n","Most of the time when a Python script fails, it will raise an Exception.\n","When the interpreter hits one of these exceptions, information about the cause of the error can be found in the *traceback*, which can be accessed from within Python.\n","\n","**Example 1:**\n","Consider the following code:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"f5zIIDMZt2Bi"},"outputs":[],"source":["def func1(a, b):\n","    return a / b\n","\n","def func2(x):\n","    a = x\n","    b = x - 1\n","    return func1(a, b)"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"C6fQuGN3t2Bj"},"outputs":[],"source":["func2(1)"]},{"cell_type":"markdown","metadata":{"id":"XoSzkiSxt2Bk"},"source":["Calling ``func2`` results in an error, and reading the printed trace lets us see exactly what happened.\n","This trace includes several lines showing the context of each step that led to the error. \\\n","In Colab, we can expand the frames and click on the blue link *\\<ipython-input-*****\\>* to open a cell at the side in which the cursor points to the line that potentially caused the error. "]},{"cell_type":"markdown","source":["**Example 2:**\n","Here is an example of common errors when writing deep learning codes. \\\n","For now, you don't have to understand what the code is doing, this example is mainly used to generate an error traceback to demonstrate how to read the traceback."],"metadata":{"id":"5qqOUXMy97SY"}},{"cell_type":"code","source":["import numpy as np\n","import torch\n","\n","def single_batch_loss(output, target, criterion):\n","  loss=criterion(output,target)\n","  return loss"],"metadata":{"id":"mTTHdhmA95a0"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["criterion = torch.nn.CrossEntropyLoss()\n","model_output=torch.tensor(np.random.rand(64, 100))\n","target_label=torch.tensor(np.ones((64,10)))"],"metadata":{"id":"pB1uLuBAHPfE"},"execution_count":null,"outputs":[]},{"cell_type":"code","source":["loss=single_batch_loss(model_output, target_label, criterion)"],"metadata":{"id":"7slmhJPEGb1w"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","source":["The error message might look very complicated, but don't be scared. Most of them are tracing into the imported python libraries, in this case `pytorch`. We can assume that there is no bug introduced in widely used libraries like `pytorch`, `numpy` and etc. Hence, when debugging, you just need to read the frames until right before entering the frames for library functions, in this case, the most recent 2 frames. \\\n","\\\n","To interpret the RuntimeError, the fastest way is to click the \"**SEARCH STACK OVERFLOW**\" button. Oftentime, you will easily find the solution to your problem there. Read the stack overflow comments before approaching TAs for help!"],"metadata":{"id":"_GViSa9DHUNR"}},{"cell_type":"markdown","metadata":{"id":"47kC0T5Xt2Bn"},"source":["## pdb: Interactive and automatic debugging\n","\n","The standard Python tool for interactive debugging is ``pdb``, the Python debugger.\n","This debugger lets the user step through the code line by line in order to see what might be causing a more difficult error.\n","\n","Perhaps the most convenient interface to debugging is the ``%debug`` magic command.\n","If you call it after hitting an exception, it will automatically open an interactive debugging prompt at the point of the exception.\n","The ``pdb`` prompt lets you explore the current state of the stack, explore the available variables, and even run Python commands!\n","\n","Let's look at the most recent exception, then do some basic tasks–print the values of ``a`` and ``b``, and type ``quit`` to quit the debugging session:"]},{"cell_type":"code","source":["func2(1)"],"metadata":{"id":"yIiET99IjLF1"},"execution_count":null,"outputs":[]},{"cell_type":"code","execution_count":null,"metadata":{"id":"76zaQeKut2Bn"},"outputs":[],"source":["%debug"]},{"cell_type":"markdown","metadata":{"id":"S08aoAOSt2Bn"},"source":["The interactive debugger allows much more than this, though–we can even step up and down through the stack and explore the values of variables there:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"7wyVi5EYt2Bo"},"outputs":[],"source":["%debug"]},{"cell_type":"markdown","metadata":{"id":"tORVTwzgt2Bo"},"source":["This allows you to quickly find out not only what caused the error, but what function calls led up to the error.\n","\n","If you'd like the debugger to launch **automatically** whenever an exception is raised, you can use the ``%pdb`` magic function to turn on this automatic behavior:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"4X4c53GJt2Bo"},"outputs":[],"source":["%pdb on\n","for i in range(-10, 10):\n","  func2(i)"]},{"cell_type":"markdown","metadata":{"id":"9Y_XXqmVt2Bo"},"source":["Finally, if you want to monitor the behaviour of your code in an interactive mode, you can add a breakpoint with the line ``pdb.set_trace()``, and use the ``next`` command to step through the lines of code interactively."]},{"cell_type":"code","source":["import pdb\n","for i in range(10): \n","  pdb.set_trace()\n","  print(i)"],"metadata":{"id":"rX_DS2WPxAkg"},"execution_count":null,"outputs":[]},{"cell_type":"markdown","metadata":{"id":"2AgcTdtat2Bp"},"source":["# Partial list of pdb commands\n","\n","There are many more available commands for interactive debugging than we've listed here; the following table contains a description of some of the more common and useful ones:\n","\n","| Command         |  Description                                                |\n","|-----------------|-------------------------------------------------------------|\n","| ``list``        | Show the current location in the file                       |\n","| ``h(elp)``      | Show a list of commands, or find help on a specific command |\n","| ``q(uit)``      | Quit the debugger and the program                           |\n","| ``c(ontinue)``  | Quit the debugger, continue in the program till next break point                 |\n","| ``n(ext)``      | Go to the next step of the program                          |\n","| ``<enter>``     | Repeat the previous command                                 |\n","| ``p(rint)``     | Print variables                                             |\n","| ``s(tep)``      | Step into a subroutine                                      |\n","| ``r(eturn)``    | Return out of a subroutine                                  |\n","\n","For more information, use the ``help`` command in the debugger, or take a look at ``pdb``'s [online documentation](https://docs.python.org/3/library/pdb.html)."]}],"metadata":{"anaconda-cloud":{},"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.5.1"},"colab":{"provenance":[{"file_id":"11DMOjbSvjdaTZy4ns3J_WlMxTq_gvtP3","timestamp":1672749129610}]}},"nbformat":4,"nbformat_minor":0}